name: Push on commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{15c29667-a85e-4029-9157-4dde27801b5a}}
        MESSAGE: "There is a new commit!"
